--- #YAML:1.0
name:                Lemonldap-NG-Manager
version:             0.85
abstract:            Perl extension for managing Lemonldap::NG Web-SSO
license:             ~
author:              
    - Xavier Guimard <x.guimard@free.fr>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           3.08
    DBI:                           0
    LWP::UserAgent:                0
    Storable:                      0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
