--- #YAML:1.0
name:               Lemonldap-NG-Manager
version:            1.2.1
abstract:           Perl extension for managing Lemonldap::NG Web-SSO
author:
    - Xavier Guimard <x.guimard@free.fr>, Clément Oudot <clement@oodo.net>, Thomas Chemineau <thomas.chemineau@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Convert::PEM:         0
    Crypt::OpenSSL::RSA:  0
    Crypt::OpenSSL::X509:  0
    IO::String:           0
requires:
    CGI:                  3.08
    File::Basename:       0
    HTML::Template:       0
    JSON:                 0
    Lemonldap::NG::Common:  1.2.1
    Lemonldap::NG::Handler:  1.2.1
    Lemonldap::NG::Portal:  1.2.1
    LWP::UserAgent:       0
    XML::LibXML:          0
    XML::LibXSLT:         0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
