# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lemonldap-NG-Manager
version:      0.72
version_from: lib/Lemonldap/NG/Manager.pm
installdirs:  site
requires:
    CGI:                           3.08
    DBI:                           0
    LWP::UserAgent:                0
    Storable:                      0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
